### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by p3lim** [CytoDev/LightDMMock#3]
- `start_session_sync` is deprecated, use `start_session`
- [L71](https://github.com/CytoDev/LightDMMock/blob/v1.0.0/mock/LightDMMock.js#L71) is a duplicate of [L69](https://github.com/CytoDev/LightDMMock/blob/v1.0.0/mock/LightDMMock.js#L69)
- Since `name` is deprecated in favor of `username`, please stop using it in your code too (see [L80](https://github.com/CytoDev/LightDMMock/blob/v1.0.0/mock/LightDMMock.js#80), [L145](https://github.com/CytoDev/LightDMMock/blob/v1.0.0/mock/LightDMMock.js#145))

**Comment by cytodev** [comment]
All of these should be resolved with [v1.1.0](../releases/tag/v1.1.0).
